### ISSUE TITLE
J1939 NAME bit representation

### ISSUE THREAD

**Issue by natkeo559** [Laixer/J1939#4]
The J1939-81 specification suggests that the `vehicle_system` field contains 7 bits preceded by 1 reserved bit (always zero).

So, querying the `vehicle_system` from bits 8-2 of byte #7 should yield the requested value. 
In your tests, `vehicle_system` = 6 and the bytes returned are:

`[0x09, 0x03, 0x4B, 0x24, 0x11, 0x05, 0x06, 0x85]`

but I think the 7th byte may be erroneous. If the reserved bit and 7 subsequent `vehicle_system` bits have distinct boundaries (i.e. byte 7 = [8765432|1] -> [0000110|0] -> 0x0C), then should we expect this?:

`[0x09, 0x03, 0x4B, 0x24, 0x11, 0x05, 0x0C, 0x85]`

**Comment by yorickdewid** [comment]
I'll have a look. I don't have all the specification docs available so you could very well be right.

**Comment by yorickdewid** [comment]
@natkeo559 Have a look at https://github.com/Laixer/J1939/pull/5
